services:
  - type: web
    name: my-service
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y cmake && \
      apt-get install -y build-essential && \
      apt-get install -y libopenblas-dev liblapack-dev && \
      apt-get install -y libx11-dev libgtk-3-dev && \
      apt-get install -y python3-dev
      pip install -r requirements.txt
    startCommand: python app.py
